language: python
sudo: false
python:
 - "3.4"
 - "3.3"
 - "2.7"
env:
 - DJANGO_VERSION=1.8.9
install:
 - pip install coverage>=4.0
 - pip install flake8
 - pip install -q Django==$DJANGO_VERSION
script:
 - coverage run setup.py test
 - coverage report -m
 - flake8 soapbox

